Webzine.WebApplication/ViewModels/TitreViewModel.cs
using System;
using System.Collections.Generic;
using Webzine.Entity;

namespace Webzine.WebApplication.ViewModels
{
    public class TitreViewModel
    {
        public string Libelle { get; set; }
        public string Chronique { get; set; }
        public Artiste Artiste { get; set; }
        public List<Commentaire> Commentaires { get; set; }
        public List<TitreStyle> TitresStyles { get; set; }
        public string UrlJaquette { get; set; }
        public int Duree { get; set; }
        public string Album { get; set; }
        public string UrlEcoute { get; set; }
        public DateTime DateCreation { get; set; }
        public int NbLikes { get; set; }
        public string GetDate
        {
            get
            {
                return DateCreation.ToString("dd/MM/yyyy");
            }
        }
        public string GetTime
        {
            get
            {
                return DateCreation.ToString("hh:mm");
            }
        }

        public Commentaire Commentaire { get; set; }
        public int IdTitre { get; set; }

        /// <summary>
        /// return the duration in string to format minutes: secondes (4:30)
        /// </summary>
        /// <returns></returns>
        public string DurationToString()
        {
            TimeSpan time = TimeSpan.FromSeconds(Duree);
            string str = time.ToString(@"mm\:ss");
            return str;
        }
    }
}

Webzine.WebApplication/Areas/API/Controllers/TitresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Webzine.Entity;
using Webzine.Repository.Contracts;

namespace Webzine.WebApplication.Areas.API.Controllers
{
    [ApiController]
    public class TitresController : ControllerBase
    {
        ITitreRepository _titreRepository;

        public TitresController(ITitreRepository titreRepository)
        {
            _titreRepository = titreRepository;
        }

        /// <summary>
        /// Permet de récupérer tout les titres en format Json
        /// </summary>
        /// <returns> Retourne tout les titres dans un format Json </returns>
        [HttpGet]
        [Route("api/Titres")]
        public IActionResult GetTitres()
        {
            try
            { 
                var result = JsonConvert.SerializeObject(_titreRepository.FindAll(), Formatting.Indented, new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
                return Ok(result);
            }
            catch (Exception)
            {
                return StatusCode(500);
            }
        }

        
        /// <summary>
        /// Permet de récupérer un titre grâce à son id
        /// </summary>
        /// <param name="id"></param>
        /// <returns> Retourne un titre dans un format Json </returns>
        [HttpGet]
        [Route("api/Titres/{id}")]
        public IActionResult GetTitre(int id)
        {
            try
            {
                var result = JsonConvert.SerializeObject(_titreRepository.Find(id), Formatting.Indented, new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
                return Ok(result);
            }
            catch (Exception)
            {

                return StatusCode(500);
            }
        }

        /// <summary>
        /// Permet d'ajouter un titre
        /// </summary>
        /// <param name="titre"></param>
        /// <returns> Retourne le titre ajouter </returns>
        [HttpPost]
        [Route("api/Titres")]
        public IActionResult PostTitre([FromBody]Titre titre)
        {
            try
            {
                _titreRepository.Add(titre);
                return Ok(JsonConvert.DeserializeObject<Titre>(JsonConvert.SerializeObject(_titreRepository.Find(titre.IdTitre), Formatting.Indented, new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore })));
            }
            catch (Exception e)
            {
                return StatusCode(500, e);
            }
        }

        /// <summary>
        /// Permet de mettre à jour un titre
        /// </summary>
        /// <param name="titre"></param>
        /// <returns> Retourne Ok </returns>
        [HttpPut]
        [Route("api/Titres/{id}")]
        public IActionResult EditTitre(int id, Titre titre)
        {
            if (id != titre.IdTitre)
            {
                return BadRequest();
            }
            try
            {
                _titreRepository.Update(titre);
                return Ok();
            }
            catch (Exception e)
            {
                return StatusCode(500, e);
            }
        }

        [HttpDelete]
        [Route("api/Titres/{id}")]
        public IActionResult DeleteTitre(int id)
        {
            try
            {
                _titreRepository.Delete(_titreRepository.Find(id));
                return Ok();
            }
            catch (Exception e)
            {

                return StatusCode(500, e);
            }
        }
    }
}

Webzine.WebApplication/Areas/Administration/Controllers/TitreController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Webzine.Entity;
using Webzine.Repository.Contracts;
using Webzine.WebApplication.Areas.Administration.ViewModels;

namespace Webzine.WebApplication.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class TitreController : Controller
    {
        private readonly ITitreRepository _titreRepository;
        private readonly IStyleRepository _styleRepository;
        private readonly IArtisteRepository _artisteRepository;

        public TitreController(ITitreRepository titreRepository , IStyleRepository styleRepository , IArtisteRepository artisteRepository)
        {
            _titreRepository = titreRepository;
            _styleRepository = styleRepository;
            _artisteRepository = artisteRepository;
        }
        public IActionResult Index()
        {
            List<Titre> titles = (List<Titre>)_titreRepository.FindAll();
            return View(titles);
        }

        public IActionResult Create()
        {
            TitleViewModel titleViewModel = new TitleViewModel { Artistes = _artisteRepository.FindAll(), Styles = _styleRepository.FindAll() };
            this.ViewData.Model = titleViewModel;
            return View();
        }

        /// <summary>
        /// Permet de créer un titre
        /// </summary>
        /// <param name="titre"></param>
        /// <returns> En cas de réussite retourne sur la page index titre, en cas d'échecs retourne sur la page create titre </returns>
        [HttpPost]
        public IActionResult Create(TitleViewModel titreVM)
        {
            try
            {
                titreVM.Titre.TitresStyles = new List<TitreStyle>();
                if (titreVM.StylesChecked != null)
                {
                    foreach (int idStyle in titreVM.StylesChecked)
                    {
                        Style style = _styleRepository.Find(idStyle);
                        if (style != null)
                        {
                            TitreStyle titreStyle = new TitreStyle()
                            {
                                IdStyle = idStyle,
                                IdTitre = titreVM.Titre.IdTitre
                            };
                            titreVM.Titre.TitresStyles.Add(titreStyle);

                        }
                    }
                }
                _titreRepository.Add(titreVM.Titre);


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        public IActionResult Edit(int id)
        {
            TitleViewModel titleViewModel = new TitleViewModel()
            {
                Artistes = _artisteRepository.FindAll(),
                Titre = _titreRepository.Find(id),
                Styles = _styleRepository.FindAll()

            };
            this.ViewData.Model = titleViewModel;
            return View();
        }

        /// <summary>
        /// Permet d'editer un tire
        /// </summary>
        /// <param name="titre"></param>
        /// <returns> En cas de réussite retourne sur la page index titre, en cas d'échecs retourne sur la page edit titre </returns>
        [HttpPost]
        public IActionResult Edit(TitleViewModel titreVM)
        {
            try
            {

                Titre titre = _titreRepository.Find(titreVM.Titre.IdTitre);
                titre.Libelle = titreVM.Titre.Libelle;
                titre.UrlEcoute = titreVM.Titre.UrlEcoute;
                titre.UrlJaquette = titreVM.Titre.UrlJaquette;
                titre.Chronique = titreVM.Titre.Chronique;
                titre.Album = titreVM.Titre.Album;
                titre.DateSortie = titreVM.Titre.DateSortie;
                titre.IdArtiste = titreVM.Titre.IdArtiste;
                titre.Duree = titreVM.Titre.Duree;
                titre.TitresStyles = new List<TitreStyle>();
                if(titreVM.StylesChecked != null)
                {
                    foreach (int idStyle in titreVM.StylesChecked)
                    {
                        Style style = _styleRepository.Find(idStyle);
                        if (style != null)
                        {
                            TitreStyle titreStyle = new TitreStyle()
                            {
                                IdStyle = idStyle,
                                IdTitre = titreVM.Titre.IdTitre
                            };
                            titre.TitresStyles.Add(titreStyle);

                        }
                    }

                }

                _titreRepository.Update(titre);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpGet]   
        public IActionResult Delete(int id)
        {
            Titre titre = _titreRepository.Find(id);
            return View(titre);
        }

        /// <summary>
        /// Permet de supprimer un titre
        /// </summary>
        /// <param name="titre"></param>
        /// <returns> En cas de réussite retourne sur la page index titre, en cas d'échecs retourne sur la page delete titre </returns>
        [HttpPost]
        [Route("administration/titre/delete/{IdTitre}")]
        public IActionResult DeleteTitre(Titre titre)
        {
            try
            {
                _titreRepository.Delete(titre);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Webzine.WebApplication/Controllers/TitreController.cs
using System;
using System.Collections.Generic;
using Webzine.Entity;
using Webzine.WebApplication.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Webzine.Repository.Contracts;
using Webzine.Business.Contracts;

namespace Webzine.WebApplication.Controllers
{
    public class TitreController : Controller
    {
        private readonly ICommentaireRepository _commentaireRepository;
        private readonly ITitreRepository _titreRepository;
        private readonly ITitreBusiness _titreBussiness;

        public TitreController(ICommentaireRepository commentaireRepository, ITitreRepository titreRepository, ITitreBusiness titreBussiness)
        {
            _commentaireRepository = commentaireRepository;
            _titreRepository = titreRepository;
            _titreBussiness = titreBussiness;
        }

        /// <summary>
        /// Return the index page to be displayed
        /// </summary>
        ///
        /// <returns>Return the index page</returns>
        /// 
        public IActionResult Index(int id)
        {
            try
            {
                Titre t = _titreRepository.Find(id);
                TitreViewModel titre = new TitreViewModel()
                {
                    Libelle = t.Libelle,
                    Chronique = t.Chronique,
                    Artiste = t.Artiste,
                    Commentaires = t.Commentaires,
                    TitresStyles = t.TitresStyles,
                    UrlJaquette = t.UrlJaquette,
                    Album = t.Album,
                    UrlEcoute = t.UrlEcoute,
                    DateCreation = t.DateSortie,
                    NbLikes = t.NbLikes,
                    IdTitre = id
                };
                this.ViewData.Model = titre;
                _titreRepository.IncrementNbLectures(t); //PAGE COUNTER
                return View();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return this.NotFound();
            }
        }

        [HttpPost]
        public IActionResult Commenter([Bind("Auteur,Contenu,IdTitre")] Commentaire commentaire)
        {
            commentaire.DateCreation = DateTime.Now;
            _commentaireRepository.Add(commentaire);
            return Redirect("/titre/" + commentaire.IdTitre);
        }

        [HttpPost]
        public IActionResult Liker(int idTitre)
        {
            try
            {
                Titre titre = _titreRepository.Find(idTitre);
                _titreBussiness.LikeTitre(titre);
                return Redirect("/titre/" + idTitre);
            }
            catch (Exception e)
            {
                return this.NotFound();
            }
        }
    }
}

Webzine.WebApplication/Views/Titre/Index.cshtml
@model TitreViewModel


<div class="row m-0 mt-3">
    <div class="col">
        <div class="container-fluid">
            <h1 class="text-primary"><a asp-controller="artiste" asp-action="index" asp-route-name="@Model.Artiste.Nom">@Model.Artiste.Nom</a> - @Model.Libelle, @Model.Album</h1>

            <div class="row d-flex align-items-center">
                <p class="m-0 ml-3"><i class="fas fa-calendar"></i> Le @Model.GetDate à @Model.GetTime</p>
                <p class="m-0 ml-4"><i class="fas fa-heart"></i> @Model.NbLikes</p>
                <p class="m-0 ml-4">
                    <i class="fas fa-tags"></i> Styles :
                    @foreach (var item in Model.TitresStyles)
                    {
                        <a asp-controller="style" asp-action="index" asp-route-libelle="@item.Style.Libelle">@item.Style.Libelle</a>
                        @if (Model.TitresStyles.Last() != item)
                        {
                            <text>-</text>
                        }
                    }
                </p>
                <form asp-controller="titre" asp-action="liker" method="post">
                    <input type="hidden" asp-for="IdTitre" value="@Model.IdTitre" />
                    <button type="submit" class="btn btn-outline-primary ml-3"><i class="fas fa-thumbs-up"></i> Like</button>
                </form>

                <a class="m-0 ml-4" asp-area="administration" asp-controller="titre" asp-action="edit" asp-route-id="@Model.IdTitre"><i class="fas fa-edit"></i> Editer</a>
            </div>
            <div class="mt-4">

                    <img class="float-right ml-2 mb-2" height="200" src="@Model.UrlJaquette" onerror="this.src='https://m.media-amazon.com/images/I/71OFozfY-cL._SS500_.jpg'" alt="image">

                
                <p class="text-justify">@Model.Chronique</p>
            </div>
            <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" src="@Model.UrlEcoute"
                        allowfullscreen></iframe>
            </div>

            <h2 class="mt-4">Donne ton avis sur le titre</h2>
            <form asp-controller="Titre" asp-action="Commenter" method="post" >
                <input type="hidden" asp-for="Commentaire.IdTitre" value="@Model.IdTitre" />
                <div class="form-group row">
                    <label asp-for="Commentaire.Auteur" class="col-sm-2 col-form-label">Nom <span class="text-danger">* </span></label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" asp-for="Commentaire.Auteur" placeholder="Votre nom (exemple : Emmanuel)">
                        <span asp-validation-for="Commentaire.Auteur" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Commentaire.Contenu" class="col-sm-2 col-form-label">Commentaire <span class="text-danger">* </span></label>
                    <div class="col-sm-10">
                        <textarea class="form-control" asp-for="Commentaire.Contenu" placeholder="Votre commentaire.."></textarea>
                        <span asp-validation-for="Commentaire.Contenu" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-10 offset-sm-2">
                        <button type="submit" class="btn btn-primary">Envoyer</button>
                    </div>
                </div>
            </form>

            <h2 class="mt-4">Commentaires</h2>
            @foreach (var item in Model.Commentaires)
            {
                <div class="row mb-4">
                    <div class="col-2 text-center overflow-hidden">
                        <img width="90" src="https://static.thenounproject.com/png/17241-200.png" alt="">
                    </div>
                    <div class="col">
                        <div class="row font-weight-bold"><span class="text-primary">@Html.DisplayFor(modelItem => item.Auteur)</span><span class="text-secondary">, le @item.DateCreation.ToShortDateString() à @item.DateCreation.ToShortTimeString()</span></div>
                        <div class="row">@Html.DisplayFor(modelItem => item.Contenu)</div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>